---
- name: Task to template root argocd application
  ansible.builtin.template:
    src: 'templates/argocd-root-app.j2'
    dest: '{{ playbook_dir }}/oc-apply/argocd-root-app.yaml'
    mode: '0644'

- name: Task to apply root argocd application
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/oc-apply/argocd-root-app.yaml'
    state: present

- name: Task to wait until the root app is applied via gitops
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: argocd-root-app-application
    namespace: openshift-gitops
  register: root_app
  until: root_app.resources is defined
  retries: 150
  delay: 10

- name: Task to wait until the root app resources[0].status.health.status is defined
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: argocd-root-app-application
    namespace: openshift-gitops
  register: root_app
  until: root_app.resources[0].status.health.status is defined
  retries: 150
  delay: 10

- name: Task to wait until the root app is synced and healthly
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: argocd-root-app-application
    namespace: openshift-gitops
  register: root_app
  until: root_app.resources[0].status.health.status == 'Healthy'
  retries: 150
  delay: 10
  
## need to patch the operator
- name: Patch certmanagers.operator.openshift.io
  kubernetes.core.k8s:
    state: patched
    api_version: operator.openshift.io/v1alpha1
    kind: CertManager
    name: cluster
    namespace: cert-manager-operator
    merge_type: 
      - merge
    definition:
      spec:
        unsupportedConfigOverrides:
          controller:
            args: 
              - "--dns01-recursive-nameservers=1.1.1.1:53,8.8.8.8:53"
              - "--dns01-recursive-nameservers-only"


- name: Task to wait until the root app is synced and healthly
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: argocd-root-app-application
    namespace: openshift-gitops
  register: root_app
  until: root_app.resources[0].status.health.status == 'Healthy'
  retries: 150
  delay: 10
                    
- name: Task to set var template_certificate to true
  ansible.builtin.set_fact:
    template_certificate: true

- name: Task to template root argocd application with certificate
  ansible.builtin.template:
    src: 'templates/argocd-root-app.j2'
    dest: '{{ playbook_dir }}/oc-apply/argocd-root-app.yaml'
    mode: '0644'

- name: Task to apply root argocd application with certificate
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/oc-apply/argocd-root-app.yaml'
    state: present

- name: Task to wait until the root app is synced and healthly
  kubernetes.core.k8s_info:
    api_version: argoproj.io/v1alpha1
    kind: Application
    name: argocd-root-app-application
    namespace: openshift-gitops
  register: root_app
  until: root_app.resources[0].status.health.status == 'Healthy'
  retries: 150
  delay: 10

- name: Patch ingresscontroller.operator default
  kubernetes.core.k8s:
    state: patched
    api_version: operator.openshift.io/v1
    kind: IngressController
    name: default
    namespace: openshift-ingress-operator
    merge_type: 
      - merge
    definition:
      spec:
        defaultCertificate:
          name: "ingress-certificate-secret"
