---
- name: Task to template the gitopsbase template
  ansible.builtin.template:
    src: 'templates/gitopsbase.j2'
    dest: '{{ playbook_dir }}/gitopsbase.yaml'
    mode: '0644'

- name: Task to apply gitops base
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/gitopsbase.yaml'
    state: present

- name: Task to remove gitops base file since it is no longer needed
  ansible.builtin.file:
    path: '{{ playbook_dir }}/gitopsbase.yaml'
    state: absent

- name: Task to patch argocd resource resource to reencrypt tls
  kubernetes.core.k8s:
    api_version: argoproj.io/v1beta1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
    state: patched
    merge_type: 
      - strategic-merge
      - merge
    definition:
      spec:
        server:
          route:
            enabled: true
            tls:
              insecureEdgeTerminationPolicy: Redirect
              termination: reencrypt
        notifications:
          enabled: true
    