---
- name: Ensure directory 'oc-apply' exists
  file:
    path: '{{ playbook_dir }}/oc-apply/'
    state: directory

- name: Task to template the gitopsbase template
  ansible.builtin.template:
    src: 'templates/gitopsbase.j2'
    dest: '{{ playbook_dir }}/oc-apply/gitopsbase.yaml'
    mode: '0644'

- name: Task to apply gitops base
  kubernetes.core.k8s:
    src: '{{ playbook_dir }}/oc-apply/gitopsbase.yaml'
    state: present

- name: Include tasks that validate the operator is installed and 'Available'
  ansible.builtin.include_tasks: validations/gitops.yaml

- name: Task to patch argocd resource resource to reencrypt tls
  kubernetes.core.k8s:
    api_version: argoproj.io/v1beta1
    kind: ArgoCD
    name: openshift-gitops
    namespace: openshift-gitops
    state: patched
    merge_type: 
      - strategic-merge
      - merge
    definition:
      spec:
        server:
          route:
            enabled: true
            tls:
              insecureEdgeTerminationPolicy: Redirect
              termination: reencrypt
    