---
# tasks file for day2operations

- name: include tasks to install Red Hat OpenShift Gitops
  ansible.builtin.include_tasks: install-gitops.yaml

- name: include tasks to install other operators
  ansible.builtin.include_tasks: install-operators.yaml