---
- name: Task to see if the ~/.kube/config file exists
  ansible.builtin.stat:
    path: '~/.kube/config'
  register: kubeconfig_stat_results

- debug:
    msg: "{{ kubeconfig_stat_results }}"
  when: debug_mode is true

- name: Task to set variable for kubeconfig status
  ansible.builtin.set_fact:
    kubeconfig_status: '{{ kubeconfig_stat_results.stat.exists }}'

