---
# https://developer.hashicorp.com/hcp/api-docs/vault-secrets#OpenAppSecret
- name: task to create get apps secret endpoint
  ansible.builtin.set_fact:
    get_apps_endpoint: '{{ hcp_api_base }}apps/{{ hcp_kubeadmin_application_name }}/open/'

- name: task to create endpoint for 
  ansible.builtin.set_fact:
    kubeadmin_api_endpoint: '{{ get_apps_endpoint }}kubeadmin'
  
- debug:
    msg: "{{ kubeadmin_api_endpoint }}"
  when: debug_mode is true

- name: task to set variable for hcp organizationID
  ansible.builtin.uri:
    url: '{{ kubeadmin_api_endpoint }}'
    method: GET
    headers: 
      Authorization: 'Bearer {{ access_token }}'
    status_code: 200
    return_content: yes
  register: hcp_kubeadmin_response

- debug:
    msg: "{{ hcp_kubeadmin_response }}"
  when: debug_mode is true

- name: task to set the kubeadmin password variable
  ansible.builtin.set_fact:
    kubeadmin_password: '{{ hcp_kubeadmin_response.json.secret.version.value }}'

- debug:
    msg: "{{ kubeadmin_password }}"
  when: debug_mode is true