---
# https://developer.hashicorp.com/hcp/api-docs/vault-secrets#OpenAppSecret
- name: task to create get apps secret endpoint
  ansible.builtin.set_fact:
    get_apps_endpoint: '{{ hcp_api_base }}apps/{{ hcp_kubeadmin_application_name }}/open'

# - name: task to create endpoint for 
#   ansible.builtin.set_fact:
#     kubeadmin_api_endpoint: '{{ get_apps_endpoint }}kubeadmin'
  
- debug:
    msg: "{{ get_apps_endpoint }}"
  when: debug_mode is true

- name: task to get kubeconfig secrets 
  ansible.builtin.uri:
    url: '{{ get_apps_endpoint }}'
    method: GET
    headers: 
      Authorization: 'Bearer {{ access_token }}'
    status_code: 200
    return_content: yes
  register: hcp_kubeconfig_response

- debug:
    msg: "{{ hcp_kubeconfig_response }}"
  when: debug_mode is true

- name: Task to extract names and values from secrets
  ansible.builtin.set_fact:
    hcp_secrets: "{{ hcp_kubeconfig_response.json | community.general.json_query(query) }}"
  vars:
    query: "secrets[*].{name: name, value: version.value}"

- debug:
    msg: "{{ hcp_secrets }}"
  when: debug_mode is true

- name: Task to assign secrets to variables
  ansible.builtin.set_fact:
    ca_auth: "{{ hcp_secrets[0].value + hcp_secrets[1].value }}"
    client_certificate_data: "{{ hcp_secrets[2].value }}"
    client_key_data: "{{ hcp_secrets[3].value }}"


- name: Task to create kubeconfig file and place in local dir 
  ansible.builtin.template:
    src: 'templates/kubeconfig.j2'
    dest: '~/.kube/config'
    mode: '0644'
